{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: npu-exporter-metrics-edge
  labels:
    fluentbit.fluent.io/enabled: "true"
    node-role.kubernetes.io/npu: "true"
spec:
  prometheusScrapeMetrics:
    tag: kubeedge.metrics.*
    host: 127.0.0.1
    port: 8082
    scrapeInterval: 30s
    metricsPath : /metrics
{{- end }}