{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluentbit-edge-gpu
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluent-bit-gpu
spec:
  image: {{ .Values.defaultImageRegistry }}{{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
  {{- if .Values.fluentbit.imagePullSecrets }}
  imagePullSecrets:
  {{- toYaml .Values.fluentbit.imagePullSecrets | nindent 8 }}
  {{- end }}
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/gpu/
  resources:
{{- toYaml .Values.fluentbit.resources | nindent 4  }}
  fluentBitConfigName: fluent-bit-config-edge-gpu
  tolerations:
    - key: node-role.kubernetes.io/edge
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: Exists
              - key: node-role.kubernetes.io/edge
                operator: Exists
  hostNetwork : true
  volumes:
    - name: host-proc
      hostPath:
        path: /proc/
    - name: host-sys
      hostPath:
        path: /sys/
  volumesMounts:
    - mountPath: /host/sys
      mountPropagation: HostToContainer
      name: host-sys
      readOnly: true
    - mountPath: /host/proc
      mountPropagation: HostToContainer
      name: host-proc
      readOnly: true
{{- end }}