{{- if .Values.Kubernetes -}}
{{- if .Values.fluentd.enable -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: {{ .Values.fluentd.name }}
  labels:
    app.kubernetes.io/name: fluentd
spec:
  globalInputs:
    - forward:
        bind: 0.0.0.0
        port: {{ .Values.fluentd.port }}
  replicas: {{ .Values.fluentd.replicas }}
  image: {{ include "fluent-operator.cloudImage" (dict "global" .Values "imageInfo" .Values.fluentbit.image) }}
  {{- if .Values.fluentd.imagePullSecrets }}
  imagePullSecrets:
  {{- toYaml .Values.fluentd.imagePullSecrets | nindent 4 }}
  {{- end }}
  resources:
  {{- toYaml .Values.fluentd.resources | nindent 4  }}
  fluentdCfgSelector:
    matchLabels:
      config.fluentd.fluent.io/enabled: "true"
  {{- if .Values.fluentd.schedulerName }}
  schedulerName: {{ .Values.fluentd.schedulerName }}
  {{- end }}
  {{- if .Values.fluentd.logLevel }}
  logLevel: {{ .Values.fluentd.logLevel }}
  {{- end }}
{{- end }}
{{- end }}
